### ISSUE TITLE
Better error for not enough targets

### ISSUE THREAD

**Issue by SamyCoenen** [stacklio/stackl#115]
# Description of feature 

When a service doesn't have enough target as specified by --replicas, for example `--replicas '{"ct_k8s_vault": 5}'` it prints all services instead of only the services with not enough targets.

# Purpose of this new feature

Better and clearer error

# Additional information

Example output 

```
{'status_code': 422, 'detail': 'Not enough targets for services {"ct_k8s_vault": ["acceptance.belgium.dome_vsphere", "production.ireland.dome_aws", "development.belgium.dome_vsphere"], "ct_k8s_vault2": ["acceptance.belgium.dome_vsphere", "production.ireland.dome_aws", "development.belgium.dome_vsphere"]}', 'headers': None}
```

**Comment by GBrawl** [comment]
I made this a little better so that it only shows the services that did not find a target.
