### ISSUE TITLE
Vault image should be configurable

### ISSUE THREAD

**Issue by BartJoris** [stacklio/stackl#202]
Right now the Vault image is hardcoded, which can cause issues like this: 

```
Failed to pull image "vault:latest": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

https://github.com/stacklio/stackl/blob/b83a784bfe62c33a2efa2802539eaa9217ef315b/stackl/agent/agent/kubernetes/secrets/vault_secret_handler.py#L93

**Comment by GBrawl** [comment]
Hi @BartJoris 

This has already been worked on and will be getting merged soon!

https://github.com/stacklio/stackl/pull/200
