### ISSUE TITLE
Outputs complexity

### ISSUE THREAD

**Issue by stgrace** [stacklio/stackl#211]
# Description of feature 

Passing outputs is too complex. Make it more dynamic/easy to use.

# Purpose of this new feature

When passing outputs, one needs to know the inner workings of Stackl and its outputs to really have an idea of what is happening. 

It should be documented how it works for each tool. Ideally there should also be a new solution to make the creation of outputs easier.

**Comment by GBrawl** [comment]
For ansible we are going to use a custom Ansible callback plugin, which will return custom stats to stackl. For terraform we are going to work with the `terraform output` command. This way we can get rid of the hard to maintain outputs sidecar container.
