### ISSUE TITLE
(check-stackl-instance.py) Script doesn't work anymore

### ISSUE THREAD

**Issue by stgrace** [stacklio/stackl#259]
Need to update the imports due to the new stackl-client 

```bash
$ check-stackl-instance
Traceback (most recent call last):
  File "/opt/stackl-cli/bin/check-stackl-instance", line 23, in <module>
    stack_instances_api = stackl_client.StackInstancesApi(
AttributeError: module 'stackl_client' has no attribute 'StackInstancesApi'
```

**Comment by mieel** [comment]
I thought this functionality is covered with the `stackl apply -s` command

**Comment by GBrawl** [comment]
Indeed, planning on deprecating the script unless there is a good argument to keep it

**Comment by stgrace** [comment]
If the -s shows what goes wrong in case of an error then I am also for deprecating the script

**Comment by stgrace** [comment]
-s is a viable alternative
